services:
  tap:
    image: "ghcr.io/bluesky-social/indigo/tap"
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:2480:2480"
    volumes:
      - "tap_data:/data"
    environment:
      TAP_SIGNAL_COLLECTION: "sh.weaver.actor.profile"
      TAP_COLLECTION_FILTERS: "sh.weaver.*"

volumes:
  tap_data:
